(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"ALP_linear",
  Authors -> {"I. Brivio, M.B. Gavela, L. Merlo, K. Mimasu, J.M. No, R. del Rey, V. Sanz"},
  Version -> "1",
  Date -> "19. 01. 2017",
  Emails -> {"ilaria.brivio@nbi.ku.dk"},
  References -> "arXiv:1701.05379",
  URLs -> "https://feynrules.irmp.ucl.ac.be/wiki/ALPsEFT"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "ax",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Ma,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MH[ ___ ] := MH;
Ma[ ___ ] := Ma;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[4] , V[1] , V[1] ] == {{(-4*I)*cw^2*ga, 0}, {0, 0}},

C[ S[4] , V[1] , V[2] ] == {{(4*I)*cw*ga*sw, 0}, {0, 0}},

C[ S[4] , V[2] , V[2] ] == {{(-4*I)*ga*sw^2, 0}, {0, 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{GS*SUNF[e3x2, e1x1, e2x1], 0}, {GS*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{I*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{((-I)*Conjugate[yd[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {((-I)*IndexDelta[e1x3, e2x3]*yd[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{((-I)*Conjugate[yl[e2x2, e1x2]])/Sqrt[2], 0}, {((-I)*yl[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{((-I)*Conjugate[yu[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/Sqrt[2], 0}, {((-I)*IndexDelta[e1x3, e2x3]*yu[e1x2, e2x2])/Sqrt[2], 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*EL, 0}, {I*EL, 0}, {I*EL, 0}, {(-I)*EL, 0}, {(-I)*EL, 0}, {I*EL, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{I*EL^2, 0}, {I*EL^2, 0}, {(-2*I)*EL^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{((-I)*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}, {((-I)*cw*EL)/sw, 0}, {((-I)*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{((-I)*EL^2)/sw^2, 0}, {((-I)*EL^2)/sw^2, 0}, {((2*I)*EL^2)/sw^2, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{((-2*I)*cw*EL^2)/sw, 0}, {(I*cw*EL^2)/sw, 0}, {(I*cw*EL^2)/sw, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(I*cw^2*EL^2)/sw^2, 0}, {(I*cw^2*EL^2)/sw^2, 0}, {((-2*I)*cw^2*EL^2)/sw^2, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{(-I)*EL*IndexDelta[e1x2, e2x2], 0}, {(-I)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{((2*I)/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {((2*I)/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{(-I/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {(-I/3)*EL*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*GS*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{(I*EL*CKM[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{(I*EL*Conjugate[CKM[e2x2, e1x2]]*IndexDelta[e1x3, e2x3])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{((I/6)*EL*(3*cw^2 - sw^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cw*sw), 0}, {(((-2*I)/3)*EL*sw*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/cw, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{((-I/6)*EL*(3*cw^2 + sw^2)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(cw*sw), 0}, {((I/3)*EL*sw*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/cw, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{((I/2)*EL*(cw^2 + sw^2)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{((-I/2)*EL*(cw - sw)*(cw + sw)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {(I*EL*sw*IndexDelta[e1x2, e2x2])/cw, 0}}

}

